export const resumeDatas = [
    "HTML",
    "CSS",
    "SCSS",
    "LESS",
    "Bootstrap",
    "Tailwind",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "JavaScript",
    "React",
    "NextJs",
    "VueJs",
    "Webpack",
]