export const SkillsDate = [
    {name: 'HTML', value: 100},
    {name: 'CSS', value: 90},
    {name: 'SCSS', value: 80},
    {name: 'Less', value: 80},
    {name: 'Bootstrap', value: 85},
    {name: 'Tailwind', value: 75},
    {name: 'Material UI', value: 70},
    {name: 'Chakra UI', value: 65},
    {name: 'Ant Design', value: 60},
    {name: 'JavaScript', value: 80},
    {name: 'React', value: 70},
    {name: 'NextJs', value: 40},
    {name: 'VueJs', value: 40},
];